website/events/urls.py
from django.conf.urls import url
from .ssr_views import StaggeredStartRaceCreator, StaggeredStartRaceDetail, \
    participants_list, enlist, StaggeredStartRaceStatus, check_for_newer_ssr
from .pitassistant_views import PitAssistantCreator, PitAssistantDetail
from .hotlap_views import HlCreator, HlEditor, HlDetail, hllaptime_add, \
    hl_download_csv

urlpatterns = [
    url(r'^s/add/$', StaggeredStartRaceCreator.as_view(),
        name='ssr_add'),
    url(r'^s/(?P<pk>\d+)/$', StaggeredStartRaceDetail.as_view(),
        name='staggeredstartrace_detail'),
    url(r'^s/(?P<pk>\d+)/participantstable.json$',
        participants_list,
        name='participantslist'),
    url(r'^s/(?P<pk>\d+)/enlist/(?P<vehicle_pk>\d+)/$',
        enlist,
        name='staggeredstartrace_enlist'),
    url(r'^s/(?P<pk>\d+)/get_status/$',
        StaggeredStartRaceStatus.as_view(),
        name='get_status'),
    url(r'^s/(?P<pk>\d+)/check_for_newer/$',
        check_for_newer_ssr,
        name='check_for_newer_ssr'),
    url(r'^p/add/$', PitAssistantCreator.as_view(),
        name='pita_add'),
    url(r'^p/(?P<pk>\d+)/$', PitAssistantDetail.as_view(),
        name='pita_detail'),
    url(r'^hl/add/$', HlCreator.as_view(),
        name='hl_add'),
    url(r'^hl/(?P<pk>\d+)/edit/$',
        HlEditor.as_view(),
        name='hl_edit'),
    url(r'^hl/(?P<pk>\d+)/csv/$',
        hl_download_csv,
        name='hl_download_csv'),
    url(r'^hl/(?P<hl_pk>\d+)/add/$',
        hllaptime_add,
        name='hl_laptime_add'),
    url(r'^hl/(?P<pk>\d+)/$',
        HlDetail.as_view(),
        name='hl_detail'),
]

website/trax/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
# from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from . import views
from tracks import views as tracks_views


urlpatterns = [
#    url(r'^admin/', admin.site.urls),
    url(r'^t/', include('tracks.urls')),
    url(r'^v/', include('vehicles.urls')),
    url(r'^r/', include('randomizer.urls')),
    url(r'^e/', include('events.urls')),
    url(r'^p/', include('players.urls')),
    # url(r'^$', cache_page(60*10)(views.Homepage.as_view()), name="homepage"),
    url(r'^$', views.Homepage.as_view(), name="homepage"),
    url(r'^accounts/login/$', views.login_view, name="login"),
    url(r'^accounts/logout/$', views.logout_view, name="logout"),
    url(r'^accounts/register/$', views.Registration.as_view(), name="register"),
    url(r'^imprint/$', TemplateView.as_view(template_name='trax/imprint.html'),
        name="imprint"),
    url(r'^robots.txt$', TemplateView.as_view(template_name='trax/imprint.html'),
                      name="DEVELOPMENTrobots.txt"),
    url(r'^miniutil/now$', views.timestamp_dev, name="DEVELOPMENTnow"),
    url(r'^epsilon/$', tracks_views.epsilon_detail, name="epsilon_detail"),
#    url(r'^grotti17/$', tracks_views.grotti17_detail, name="grotti17_detail"),
    url(r'^unaffordable/$', tracks_views.unaffordable_detail,
        name="unaffordable_detail"),
    url(r'^tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/events/models.py
import datetime
import json
import os

import bleach
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
# from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _

from trax.choices import RACE_STATES, SSR_ALGORITHMS, PITLOGENTRIES

#class StaggeredPlaylist(models.Model):
#    title = models.CharField(max_length=256)
#    creator = models.ForeignKey('players.Player')
#    created = models.DateTimeField(auto_now_add=True)
#    platform = models.CharField(max_length=8,
#                                choices=PLATFORM_CHOICES, default='pc')


class StaggeredStartRace(models.Model):
    track = models.ForeignKey('tracks.Track')
    vehicle_class = models.ForeignKey('vehicles.VehicleClass', null=True)
    laps = models.PositiveSmallIntegerField(default=5)
    host = models.ForeignKey('players.Player')
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=RACE_STATES.choices,
                              default=RACE_STATES.planning)
    hosting_date = models.DateTimeField(null=True)
    link = models.URLField(
        null=True, help_text=_("could be a screenshot URL of the results"))
    comment = models.TextField(default="", blank=True)
    start_timestamp = models.DateTimeField(null=True, default=None)
    per_overtake_deficit_millis = models.IntegerField(null=True, default=600)
#    staggeredplaylist = models.ForeignKey('StaggeredPlaylist', null=True)
#    number_in_playlist = models.PositiveSmallIntegerField(default=0)
    algorithm = models.CharField(max_length=2, choices=SSR_ALGORITHMS,
                                 default='SO')

    def __str__(self):
        hosting_date = self.hosting_date and \
                       self.hosting_date.strftime('%Y-%m-%d') or \
                       'not defined'
        return '{0} by {1} ({2})'.format(
            self.track.title, self.host.username,
            hosting_date)

    def get_absolute_url(self):
        return reverse_lazy('staggeredstartrace_detail',
                            kwargs={'pk': self.pk})

    @property
    def json_url(self):
        return os.path.join(
            settings.STATIC_URL, 'ssr',
            '{0}.json'.format(self.pk))

    def update_json(self):
        """saves the current whole json state for faster access"""
        players = []
        current_index = -1
        already_seen_a_vehicle = False
        racetime = 0
        qset = self.ssrparticipation_set.all()

        # in case some players did not choose a car,
        # we need to ignore them when racing starts
        if self.status == RACE_STATES.running:
            qset = qset.exclude(estimated_laptime__isnull=True)

        for s in qset.order_by('-estimated_laptime'):
            current_index += 1
            estimated_laptime = 0
            if s.estimated_laptime:
                estimated_laptime = s.estimated_laptime
            if not already_seen_a_vehicle and estimated_laptime:
                already_seen_a_vehicle = True
                racetime = estimated_laptime * self.laps
            start_after_first = datetime.timedelta(
                milliseconds=racetime - (estimated_laptime * self.laps))
            minutes = int(start_after_first.seconds / 60)
            seconds = int(start_after_first.seconds % 60)
            millis = int(start_after_first.microseconds / 1000)
            startafterstr = '{0:02d}:{1:02d}.{2:03d}'.format(
                minutes, seconds, millis)
            newdict = {'username': s.player.username,
                            'pk': s.player.pk,
                            'vehicle': s.vehicle and s.vehicle.name or '',
                            'estimated_laptime': estimated_laptime,
                            'start_after_first': startafterstr,
                            }
            if s.start_timestamp:
                newdict['timestamp'] = int(s.start_timestamp.timestamp()*1000)
            players.append(newdict)
        dct = {'status': self.status, 'players': players}
        filename = os.path.join(
            settings.STATIC_ROOT, 'ssr',
            '{0}.json'.format(self.pk))
        with open(filename, 'w') as f:
            f.write(json.dumps({'data': dct}, separators=(',', ':')))


class SSRParticipation(models.Model):
    player = models.ForeignKey("players.Player")
    vehicle = models.ForeignKey("vehicles.Vehicle", null=True, blank=True)
    staggeredstartrace = models.ForeignKey('StaggeredStartRace')
    estimated_laptime = models.IntegerField(
        null=True, help_text='according to calculations the estimated '
                             'total racing net time for one lap.')
    laptime = models.ForeignKey("tracks.Laptime", null=True)
    start_timestamp = models.DateTimeField(null=True)

    class Meta:
        ordering = ('start_timestamp', 'player__username')

    @property
    def start_in_millis(self):
        tdobj = self.start_timestamp - datetime.datetime.now(
            tz=self.start_timestamp.tzinfo)
        return int(tdobj.total_seconds() * 1000)


class PitAssistant(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField(default='', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=RACE_STATES.choices,
                              default=RACE_STATES.planning)
    pitstop_seconds = models.PositiveSmallIntegerField(default=30)
    start_timestamp = models.DateTimeField(null=True)
    owner = models.ForeignKey("players.Player", null=True)

    def get_absolute_url(self):
        return reverse_lazy('pita_detail',
                            kwargs={'pk': self.pk})

    @property
    def json_root(self):
        return os.path.join(
            settings.STATIC_URL, 'pitassistant',
            '{0}/'.format(self.pk))


class PitAParticipation(models.Model):
    player = models.ForeignKey("players.Player")
    pitassistant = models.ForeignKey('events.PitAssistant')


class PitLogEntry(models.Model):
    pitassistant = models.ForeignKey('events.PitAssistant')
    ingameseconds_created = models.IntegerField()
    text = models.CharField(max_length=1024, default='', blank=True)
    entrytype = models.CharField(max_length=1, choices=PITLOGENTRIES.choices,
                                 default=PITLOGENTRIES.pitstop)
    for_player = models.ForeignKey("players.Player", null=True)


class Hotlapping(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField(default='', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey("players.Player", null=True)
    track = models.ForeignKey("tracks.Track")
    vehicles = models.ManyToManyField(to="vehicles.Vehicle",
                                      related_name="vehicles", )
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    closing_text = models.TextField(default='', blank=True)
    divisions_text = models.TextField(default='10:Top Ten\n20:Rest of the starting grid\n999:Not fast enough')
    entries = models.ManyToManyField("tracks.Laptime",
                                     through="HotlappingLaptime",
                                     through_fields=('hotlapping', 'laptime')
                                     )
    time_period_text = models.CharField(default='', blank=True,
                                        max_length=256)
    webhook_url = models.URLField(null=True)

    class Meta:
        ordering = ('-end_date', 'pk')

    def get_absolute_url(self):
        return reverse_lazy('hl_detail',
                            kwargs={'pk': self.pk})


class HotlappingLaptime(models.Model):
    approved = models.BooleanField(default=False)
    hotlapping = models.ForeignKey("events.Hotlapping", on_delete=models.CASCADE)
    laptime = models.ForeignKey("tracks.Laptime", on_delete=models.CASCADE)

website/events/templates/events/enlist_form.html
<div class="row">
  <div class="col-sm-12">
    <button class="btn btn-default big" id="togglevehiclelist" data-toggle="collapse" data-target="#showvehiclelist">Choose your car</button>
    <div class="row" id="showvehiclelist">
      {% for listpart in vehicle_list %}
        <div class="col-xs-6">
          {% for entry in listpart %}
            <button class="enlist_btn btn btn-sm form-control btn-default"
                    onclick="enlist_car(this);"
                    value="{% url 'staggeredstartrace_enlist' pk=object.pk vehicle_pk=entry.pk %}">{{ entry.name }}</button>

          {% endfor %}
        </div>
      {% endfor %}
    </div>
  </div>
</div>

website/events/templates/events/gogogotestbutton.html
<audio id="gogogo"></audio>
<button class="btn btn-default" onclick="teststart();">
<span class="glyphicon glyphicon-music"></span> Test the start signal</button>

website/events/templates/events/host_detail_snippet.html
<h3>Invite players</h3>
<p>Use this link to invite some players:
  <input
      class="form-control"
      type="text"
      value="{{ invite_url }}"
      onClick="this.select();">
</p>
{% include "events/info_snippet.html" %}
<div class="panel panel-default">
  <div class="panel-body">
    <form action="." method="get" id="startraceform">
      <div class="row">
        <div class="col-xs-6">
          Start in about
        </div>
        <div class="col-xs-6 form-inline">
          <input value="15" style="width:5em;" type="text"
                 class="form-control" name="start_in_secs"> seconds
        </div>
        <div class="col-xs-6">
          Per overtake time deficit
        </div>
        <div class="col-xs-6 form-inline">
          <input value="600" style="width:5em;" type="text"
                 class="form-control" name="per_overtake_deficit_millis"> millisecs
        </div>
        <div class="col-xs-12">
          (for every car a player has to overtake, this amount of milliseconds
          will be subtracted from his start time delay,
          so he is not being punished for being in a faster vehicle.)
        </div>
        <div class="col-xs-12 text-center">
          <button id="submitstartraceform" class="btn btn-primary btn-block">Ok, let's do it!</button>
        </div>
      </div>
      <div class="form-inline">
      </div>
      <div class="form-inline">
      </div>
    </form>
  </div>
</div>

<h3>What to do next?</h3>
<p>Choose your vehicle if you want to drive too. (Click on the
  corresponding link.)</p>
<p>As soon as every player has joined,
  you can tell me when to start the race.
  Just fill out the form, and off you go!</p>
<p>Everyone will get a visual and audible signal when it's time for them to
  start racing.</p>
<p>Interested how it will sound and look? Find out here:
  {% include "events/gogogotestbutton.html" %}
</p>

website/events/templates/events/hotlapping_detail.html
{% extends "events/base.html" %}
{% load i18n %}
{% load static %}
{% load compress %}
{% load bootstrap3 %}
{% load widget_tweaks %}
{% load trax_extras %}

{% block title %}Hotlapping "{{ object.title }}" {% endblock %}
{% block content %}

  <div id="addhllaptime" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"
                  aria-hidden="true">&times;</button>
        </div>
        {% include "events/add_hl_laptime_form.html" %}
      </div>
    </div>
  </div>


  <h1>{{ object.title }}

    <small class="pull-right">
      {% if entry_possible %}
        <a href="#addhllaptime" role="button" class="btn btn-default" data-toggle="modal">
          <span class="glyphicon glyphicon-road" aria-hidden="true"></span>
          Enter a lap time…</a>
      {% endif %}

      <a href="{{ object.track.get_absolute_url }}" class="btn btn-default">
        Detailed track info</a>
      {% if request.user == object.owner %}
        <a href="{% url "hl_edit" object.pk %}" role="button" class="btn btn-default">
          <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
          Edit event</a>
        <a href="{% url "hl_download_csv" object.pk %}" role="button" class="btn btn-default">
          <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
          CSV download</a>
      {% endif %}
    </small>
  </h1>
  <p><small>
    {% if object.time_period_text %}
      {{ object.time_period_text }}
    {% else %}
     {{ object.start_date|date:"Y-m-d H:i" }} – {{ object.end_date|date:"Y-m-d H:i" }}
    {% endif %}
    </small></p>
  <p>{{ object.description | urlizetrunc:25 | url_target_blank | linebreaksbr }}</p>
  {% if entry_possible %}{% else %}
    <p>The event is over. No more lap times can be entered.</p>
  {% endif %}

  <div class="row">
    {% for division in divisions %}
      <div class="col-md-6">
      <h2>{{ division.0 }}</h2>
        <table class="table table-bordered table-condensed table-striped">
          <thead>
          <th>#</th>
          <th>Name</th>
          <th>Vehicle</th>
          <th><span class="glyphicon glyphicon-link"></span></th>
          <th>Date</th>
          <th>Lap time</th>
          </thead>
          <tbody>
            {% for obj in division.1 %}
              <tr>
                <td>{{ obj.place|default:'—' }}</td>
              <td>{{ obj.laptime.player|default:'–' }}</td>
                <td>{{ obj.laptime.vehicle.name|default:'–' }}</td>
              <td>
                {% if obj.laptime.link %}
                  <a href="{{ obj.laptime.link }}" target="_blank"><span class="glyphicon glyphicon-link"></span></a></td>
                  {% else %}
                  —
                {% endif %}
                <td>{{ obj.laptime.created|date:"Y-m-d"|default:'–' }}</td>
              <td>{{ obj.laptime.duration|default:'–' }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% endfor %}
  </div>

{% endblock %}

website/events/templates/events/hotlapping_form.html
{% extends "events/base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load widget_tweaks %}


{% block title %}Race creator{% endblock %}
{% block content %}

  {% if form.instance.pk %}
    <h1>Edit "{{ form.instance.title }}"</h1>
  {% else %}
    <h1>Create a Hotlapping event</h1>
  {% endif %}

  <div class="row" >
    <form action="." method="post" >
      <div class="col-md-6">
        {% csrf_token %}
        Title of your event
        {% render_field form.title class="form-control" %}

        Enter a description.
        <small>(Any "http"-links you enter will be converted to clickable links)</small>
        {% render_field form.description class="form-control" %}

        Structure
        {% render_field form.divisions_text class="form-control" %}
        <p><small>Specify the number of players for each table, followed by a colon ":" and the title of the table.
          <br>This field is <b>required</b>. If you just want one table, type "1000:Drivers" or something.
          <br>Abe.Cede was too lazy to implement some nice validator. It's up to you to be smart enough to enter this
          field correctly.</small></p>
      </div>
      <div class="col-md-6">
        Track:
        {% render_field form.track class="combobox form-control" %}
        Vehicles:
        {% render_field form.vehicles class="form-control" %}
        <hr>
        Start date:
        {% render_field form.start_date class="form-control" %}
        End date:
        {% render_field form.end_date class="form-control" %}
        <hr>
        If you don't want to show start date and end date, enter some text here
        which will be shown instead of the real time period.
        {% render_field form.time_period_text class="form-control" %}
        <hr>
        If you have a webhook url (e.g. for your own Discord server), I can
        post new verified laptimes having a video included with this url.
        {% render_field form.webhook_url class="form-control" %}
      </div>
      <div class="col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Okay!</button>
      </div>
    </form>
  </div>

{% endblock %}


{% block trax_extra_script %}
  <script type="text/javascript">
    $(document).ready(function() {
      $('#id_vehicles').multiselect({
        maxHeight: 300,
        includeSelectAllOption: true,
        enableFiltering: true,
        enableClickableOptGroups: true,
        numberDisplayed:6,
        enableCaseInsensitiveFiltering: true
      });

      $('#id_start_date').datetimepicker({
        format:'YYYY-MM-DD HH:mm'
      });
      $('#id_end_date').datetimepicker({
        format:'YYYY-MM-DD HH:mm'
      });
      $("#id_start_date").on("dp.change", function (e) {
        $('#id_end_date').data("DateTimePicker").minDate(e.date);
      });
      $("#id_end_date").on("dp.change", function (e) {
        $('#id_start_date').data("DateTimePicker").maxDate(e.date);
      });
    });

  </script>

{% endblock %}

website/events/templates/events/info_snippet.html
<div class="alert alert-info">
  <h4 class="text-center"><span class="glyphicon glyphicon-alert" aria-hidden="true"></span>
    This one's important!
    <span class="glyphicon glyphicon-alert" aria-hidden="true"></span></h4>
  <p>You will <b>not</b> hear the sound of the start signal if you minimize
    your browser window, so <b>keep it open</b> in the background!
    Do <b>not</b> click on the little "_" icon of the browser window's upper right corner!</p>
  <p>Also, this feature has only been tested in Chrome, Firefox, Opera, Safari and Chromium browsers.
    Use at your own risk in other browsers like Internet Explorer etc.</p>
  <h5>Mobile phone users</h5>
  <p>If you use this tool on a phone, you will probably not hear any sound, because
  phones don't usually allow sound to be played without direct interaction of a user.
  <b>But</b> you will see the screen flash green, so that should hopefully be enough notice for you.</p>
</div>

website/events/templates/events/old_staggeredstartrace_detail.html
{% extends "events/base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load widget_tweaks %}

{% block title %}{{ object.track }} {% endblock %}
{% block content %}

  <div class="hidden" id="event_status">{{ object.status }}</div>

  {% if object.status == 'i' %}
    <h1>{{ object.track }}</h1>
    <div class="row" id="showform" >
      <div class="col-md-4">
      <dl class="dl-horizontal">
        <dt>Host:</dt><dd>{{ object.host }}</dd>
        <dt>Vehicle class:</dt><dd>{{ object.vehicle_class }}</dd>
        <dt>Number of laps:</dt><dd>{{ object.laps }}</dd>

      </dl>
        {% if request.user.username == object.host.username %}
          {% include "events/host_detail_snippet.html" %}
        {% else %}
          {% include "events/participant_detail_snippet.html" %}
        {% endif %}
      </div>
      <div class="col-md-8" id="playerlist">
        {% include "events/enlist_form.html" %}
        <h2>Current players</h2>
        <table id="participantstable" class="table table-striped table-bordered">
          <thead>
          <tr>
            <th>Name</th>
            <th>Vehicle</th>
          </tr>
          </thead>
          <tbody>
          </tbody>

        </table>
      </div>
    </div>
  {% endif %}

  {% if object.status == 'r' %}
    <h1 id="userpos"></h1>
    <form action="." method="post">
    {% csrf_token %}
    After the race please tell me your best lap time: <input type="text" name="personal_laptime">
      (MM:SS.milli)
    <button type="submit" class="btn btn-primary">Save</button>
    </form>
    <audio id="gogogo"></audio>
    <table class="table">
      <thead>
      <th>&nbsp;</th>
      <th>Name</th>
      <th>Vehicle</th>
      <tbody>
      {% for p in object.ssrparticipation_set.all %}
        <tr>
          <td id="line{{ p.pk }}"><img id="img{{ p.pk }}" src="/static/red_light.png" width="24" height="24"></td>
          <td>{{ p.player }}</td>
          <td>{{ p.vehicle }}</td>
        </tr>
      {% endfor %}
      </tbody>
      <tfoot><tr><td></td><td></td><td></td></tr></tfoot>
      </thead>
    </table>
  {% endif %}

{% endblock %}

{% block trax_extra_script %}
  <script src="/static/serverdate.js"></script>
  <script src="/static/mespeak/mespeak.js"></script>
  <script src="/static/staggeredstart.js"></script>
  <!-- script src="https://dl.dropboxusercontent.com/s/h0pv1d0gjrtvbce/mespeak.js"></script -->
  {% if object.status == 'r' %}
    <script>
        meSpeak.loadConfig("/static/mespeak/mespeak_config.json");
        meSpeak.loadVoice('/static/mespeak/voices/en/en-us.json');
        $(document).ready(function() {
            {% for p in object.ssrparticipation_set.all %}
                {% if p.player.pk == request.user.pk %}
                    $("#userpos").text('You are in position n° ' + {{ forloop.counter }} + '.');
                    {% if p.start_in_millis > 2000 %}
                        {% if p.start_in_millis > 9000 %}
                        meSpeak.speak('You are in pohsition, number ' + {{ forloop.counter }} + '.',
                            {variant:"f5", wordgap:5});
                        {% endif %}
                        setTimeout( function() {usergreenlight( {{ p.pk }} ); }, {{ p.start_in_millis }} );
                        setTimeout( function() {meSpeak.speak("Get ready!", {variant:"f5", wordgap:5}); },
                            {{ p.start_in_millis }} - 5000 );
                    {% else %}
                        setTimeout( function() { greenlight( {{ p.pk }} ); }, {{ p.start_in_millis }} );
                    {% endif %}
                {% else %}
                    setTimeout( function() { greenlight( {{ p.pk }} ); }, {{ p.start_in_millis }} );
                {% endif %}

            {% endfor %}
        });
    </script>
  {% endif %}
{% endblock %}

website/events/templates/events/pita_finished.html
finished

website/events/templates/events/pita_initializing.html
initializing

website/events/templates/events/pita_running.html
running

website/events/templates/events/staggeredstartrace_detail.html
{% extends "events/base.html" %}
{% load i18n %}
{% load static %}
{% load compress %}
{% load bootstrap3 %}
{% load widget_tweaks %}

{% block title %}{{ object.track }} {% endblock %}
{% block content %}

  <div class="hidden" id="event_status">{{ object.status }}</div>
  <div class="hidden" id="json_url">{{ object.json_url }}</div>


  <h1><small>{{ object.laps }} laps on </small>{{ object.track }} <small>[{{ object.track.platform }}] hosted by {{ object.host }}
    | Algorithm: {{ object.get_algorithm_display }}</small></h1>

  <div id="loading" class="row text-center">
    <img src="/static/infinity.gif"><br>
    <small>Loading...</small>
    <img src="/static/green_light.png" class="hide" alt=""/>
    <img src="/static/red_light.png" class="hide" alt=""/>

  </div>

  <div id="twocols" class="row" style="display:none">
    <div class="col-md-6">
    {% if object.comment %}
  <h3>Information for this race</h3>
  {{ object.comment }}
  <hr>
{% endif %}

      {% if request.user.username == object.host.username %}
        {% include "events/host_detail_snippet.html" %}
      {% else %}
        {% include "events/participant_detail_snippet.html" %}
      {% endif %}
    </div>

    <div class="col-md-6">


      {% include "events/enlist_form.html" %}
      <h3><span id="num_participants">0</span> registered players</h3>
      <table class="table table-bordered table-condensed" id="participants">
        <thead>
        <tr class="info">
          <td class="col-md-1">&nbsp;</td>
          <td class="col-md-2">Player</td>
          <td class="col-md-2">Vehicle</td>
          <td class="col-md-1">Start</td>
        </tr>
        </thead>
        <tbody id="participantsbody">
        </tbody>
      </table>

    </div>
  </div>

  <div id="racescreen" style="display:none">
    <table class="table table-bordered table-condensed" id="participants">
      <thead>
      <tr class="info">
        <td class="col-md-1">&nbsp;</td>
        <td class="col-md-2">Player</td>
        <td class="col-md-2">Vehicle</td>
        <td class="col-md-1">Start</td>
      </tr>
      </thead>
      <tbody id="racebody">
      </tbody>
    </table>
  </div>

  <div id="resultform" class="row" style="display:none">
    <div class="col-md-12">
      <h1>One little thing to do...</h1>
    </div>
    <div class="col-md-5">
      <form action="." method="post">
        {% csrf_token %}
        <p>After the race please tell me your best lap time:<br />
          <input name="personal_laptime"
                 required
                 pattern="^\d{1,2}:\d{1,2}\.\d\d?\d?$"
                 id="seconds"
                 title="e.g. '1:03.123'"
                 alt="alttext"
                 type="text">(MM:SS.milli)
        </p>
        <button type="submit" class="btn btn-primary">Save</button>
      </form></div>
    <div class="col-md-2">&nbsp;</div>

    <div class="col-md-5">
      <form action="." method="post">
        {% csrf_token %}
        <p>Nah, better not. My laptime was abysmal.</p>
        <input name="personal_laptime" value="-1" type="hidden">
        <button type="submit" class="btn btn-primary">Don't save.</button>
      </form>
    </div>
  </div>
{% endblock %}
{% block trax_extra_script %}
  {% compress js %}
    <script src="/static/mespeak/mespeak.js"></script>
    <script src="{% static 'serverdate2.js' %}"></script>
    <script src="{% static 'staggeredstart2.js' %}"></script>
  {% endcompress %}
{% endblock %}