website/trax/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
# from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from . import views
from tracks import views as tracks_views


urlpatterns = [
#    url(r'^admin/', admin.site.urls),
    url(r'^t/', include('tracks.urls')),
    url(r'^v/', include('vehicles.urls')),
    url(r'^r/', include('randomizer.urls')),
    url(r'^e/', include('events.urls')),
    url(r'^p/', include('players.urls')),
    # url(r'^$', cache_page(60*10)(views.Homepage.as_view()), name="homepage"),
    url(r'^$', views.Homepage.as_view(), name="homepage"),
    url(r'^accounts/login/$', views.login_view, name="login"),
    url(r'^accounts/logout/$', views.logout_view, name="logout"),
    url(r'^accounts/register/$', views.Registration.as_view(), name="register"),
    url(r'^imprint/$', TemplateView.as_view(template_name='trax/imprint.html'),
        name="imprint"),
    url(r'^robots.txt$', TemplateView.as_view(template_name='trax/imprint.html'),
                      name="DEVELOPMENTrobots.txt"),
    url(r'^miniutil/now$', views.timestamp_dev, name="DEVELOPMENTnow"),
    url(r'^epsilon/$', tracks_views.epsilon_detail, name="epsilon_detail"),
#    url(r'^grotti17/$', tracks_views.grotti17_detail, name="grotti17_detail"),
    url(r'^unaffordable/$', tracks_views.unaffordable_detail,
        name="unaffordable_detail"),
    url(r'^tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/tracks/models.py
from urllib.parse import urlparse
from easy_thumbnails.fields import ThumbnailerImageField
from threadlocals.threadlocals import get_current_request
from trax.choices import GAME_MODES, ROUTE_TYPES, PLATFORM_CHOICES
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from embed_video.fields import EmbedVideoField

from trax.utils import get_object_by_string


class TrackQueryset(models.query.QuerySet):
    def my(self):
        request = get_current_request()
        if request and request.user.is_authenticated():
            return self.filter(creator=request.user)
        return self.all()


class TrackManager(models.Manager):
    def get_queryset(self):
        default_platforms = 'pc ps4 xb1'
        qs = TrackQueryset(self.model, using=self._db)
        request = get_current_request()
        if request:
            platforms = request.COOKIES.get('traxpf', default_platforms)
            platforms = platforms.replace("%20", " ").split()
            if not platforms:
                platforms = default_platforms.split()
            qs = qs.filter(platform__in=platforms)
        return qs

    def my(self):
        return self.get_queryset().my()


class Track(models.Model):
    objects = TrackManager()

    title = models.CharField(unique=True, max_length=256)
    description = models.TextField(blank=True, default='')
    author = models.CharField(max_length=64, default='', null=False)
    creator = models.ForeignKey("players.Player", null=True)
    link = models.URLField(null=True)
    video = EmbedVideoField(null=True, blank=True)
    game_mode = models.CharField(max_length=8, choices=GAME_MODES,
                                 default=GAME_MODES[0][0])
    route_type = models.CharField(max_length=1, choices=ROUTE_TYPES,
                                  default=ROUTE_TYPES[0][0])
    route_length_km = models.FloatField(null=True)
    num_players = models.PositiveSmallIntegerField(null=True)
    typical_laptime = models.IntegerField(
        help_text=_('How many seconds does it typically take for a fully '
                    'customized car to finish a lap with no major issues?'),
        null=True)
    pit_lane = models.BooleanField(
        help_text=_('Does the track have a pit lane with repair icons?'),
        default=False)
    surface_street = models.SmallIntegerField(
        help_text=_('Typical streets in Los Santos'), default=0)
    surface_road = models.SmallIntegerField(
        help_text=_('Tarmac roads e.g. Blaine County'), default=0)
    surface_dirt = models.SmallIntegerField(
        help_text=_('Non-tarmac dirt roads e.g. in Sandy Shores'), default=0)
    surface_flat = models.SmallIntegerField(
        help_text=_('Tarmac and concrete surface at LS airport, Fort '
                    'Zancudo and similar areas. Highways as well.'), default=0)
    surface_stunt = models.SmallIntegerField(
        help_text=_('Surfaces made with stunt props.'), default=0)
    surface_offroad = models.SmallIntegerField(
        help_text=_('Anything offroad e.g. forests, fields, grasslands, '
                    'desert'), default=0)
    elevation_changes = models.SmallIntegerField(
        help_text=_("From airport-flat (0), to Tongva Hills (50) to "
                    "rollercoastery ups and downs (100)."),
        default=0)
    car_classes = models.ManyToManyField('vehicles.VehicleClass')
    platform = models.CharField(max_length=8,
                                choices=PLATFORM_CHOICES, default='pc')
    reference_track = models.BooleanField(
        default=False, help_text=_("Is this a reference track for laptimes?"))
    image = ThumbnailerImageField(upload_to='trackimages', blank=True)
    num_hairpins = models.SmallIntegerField(default=0)
    num_slow_turns = models.SmallIntegerField(default=0)
    num_fast_turns = models.SmallIntegerField(default=0)
    num_slow_chicanes = models.SmallIntegerField(default=0)
    num_fast_chicanes = models.SmallIntegerField(default=0)
    include_in_halloffame = models.BooleanField(default=True)

    @property
    def terrains(self):
        return [
            {'type': _('Street'), 'perc': self.surface_street, 'class': 'st'},
            {'type': _('Road'), 'perc': self.surface_road, 'class': 'ro'},
            {'type': _('Dirt'), 'perc': self.surface_dirt, 'class': 'di'},
            {'type': _('Flat'), 'perc': self.surface_flat, 'class': 'fl'},
            {'type': _('Stunt'), 'perc': self.surface_stunt, 'class': 's'},
            {'type': _('Offroad'), 'perc': self.surface_offroad, 'class': 'of'},
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('track_detail', args=[str(self.pk)])

    @property
    def duration(self):
        minu, seco = divmod(self.typical_laptime, 60)
        return "{0}:{1:02}".format(int(minu), int(seco))

    @property
    def route_length(self, unit='km'):
        return "{:.02f}".format(self.route_length_km)


def get_track_by_string(s):
    """returns a track object, if something with a score > 70 could be found."""
    return get_object_by_string(s, Track, 'title')


class Laptime(models.Model):
    track = models.ForeignKey("tracks.Track")
    player = models.ForeignKey("players.Player")
    created = models.DateTimeField(auto_now_add=True)
    recorded = models.DateField(null=True)
    vehicle = models.ForeignKey("vehicles.Vehicle")
    millis = models.IntegerField(default=0)
    millis_per_km = models.IntegerField(default=0)
    comment = models.TextField(default='', null=True, blank=True)
    video = EmbedVideoField(null=True)
    link = models.URLField(null=True)
    pc_60fps = models.BooleanField(default=False)

    class Meta:
        ordering=['-pk', ]

    def __str__(self):
        return '{0} {1}'.format(self.player.username,
                                self.vehicle.name)

    @property
    def duration(self):
        seco, mill = divmod(self.millis, 1000)
        minu, seco = divmod(seco, 60)
        return "{0}:{1:02}.{2:03}".format(int(minu), int(seco), int(mill))


    @property
    def km_per_h(self):
        if self.millis_per_km != 0:
            return '{:.3f}'.format(
                (1.0 / self.millis_per_km ) * 1000 * 3600
            )
        return '?'

    @property
    def linktype(self):
        """returns "l" for generic link, "v" for videolink, "" if no link at all"""
        hostname = urlparse(self.link).hostname
        VIDEOSITES = ('vimeo', 'youtu', 'dailymotio', 'twitch')
        if not hostname:
            return ""
        for hostpart in VIDEOSITES:
            if hostname.startswith(hostpart) or '.' + hostpart in hostname:
                return "film"
        return "link"

website/trax/views.py
from captcha.fields import ReCaptchaField
from collections import OrderedDict

from django.contrib.auth import get_user_model, logout, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.forms import Form, ModelForm
from django import forms
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.hashers import make_password

from players.models import Player
from tracks.models import Track, Laptime

_User = get_user_model()

# @method_decorator(login_required, name='dispatch')
class Homepage(TemplateView):
    template_name = "trax/homepage.html"

    def get_context_data(self, **kwargs):
        context = super(Homepage, self).get_context_data(**kwargs)
        tracks = Track.objects.all().order_by('-pk')[:10]
        context['tracks'] = tracks
        context['toplaps'] = self.get_top_laps()
        return context

    def get_top_laps(self, num_items=5):
        all_laptimes = Laptime.objects.filter(
            link__isnull=False, track__include_in_halloffame=True).exclude(link='')\
            .select_related("vehicle")\
            .extra(select={'quickness': 'millis_per_km*1.0/cc_millis_per_km'})\
            .order_by('quickness')
        l = []
        track_pks_loaded = []
        num_tracks_found = 0
        for laptime in all_laptimes:
            if laptime.track.pk not in track_pks_loaded:
                track_pks_loaded.append(laptime.track.pk)
                num_tracks_found += 1
                l.append(laptime)
            if num_tracks_found > 10:
                break
        return l



class RegistrationForm(ModelForm):
    class Meta:
        model = Player
        fields = ['username']
    email = forms.EmailField(
        label=_("E-Mail"),
        help_text=_("You don't really need to enter an e-mail address. "
                    "Although it would help you in recovering your acccount "
                    "in case you should forget your password."),
        required=False)
    password1 = forms.CharField(label='Password',
                                max_length=100,
                                widget=forms.widgets.PasswordInput)
    password2 = forms.CharField(label='Password (again)',
                                max_length=100,
                                widget=forms.PasswordInput)
    captcha = ReCaptchaField()

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        if Player.objects.filter(username=username).count() != 0:
            raise forms.ValidationError(_('This username already exists here. You can send a Social Club message to "Abe.Cede" to solve the issue.'))
        return username

    def clean(self):
        p1 = self.cleaned_data.get("password1")
        p2 = self.cleaned_data.get("password2")

        if p1 != p2:
            raise forms.ValidationError(
                _('Your passwords were not identical. Please try again.'))
        return self.cleaned_data


class Registration(TemplateView):
    template_name = "registration/register.html"

    def get(self, request, **kwargs):
        next_url = request.GET.get('next', '/')
        form = RegistrationForm()
        return render(request, self.template_name, {
            'form': form, 'next': next_url})

    def post(self, request, **kwargs):
        form = RegistrationForm(request.POST)
        next_url = request.POST.get('next', '/')
        if not form.is_valid():
            return render(request, self.template_name, {
                'form':form, 'next': next_url})
        user = Player(username=form.cleaned_data['username'],
                      email=form.cleaned_data['email'])
        user.set_password(form.cleaned_data['password1'])
        user.save()
        login(request, user)
        return HttpResponseRedirect(next_url)


@never_cache
def logout_view(request):
    logout(request)
    resp = HttpResponseRedirect('/')
    resp.set_cookie('username', '-')
    return resp


class TraxAuthenticationForm(AuthenticationForm):
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        return username


def login_view(request):
    resp = auth_views.login(request, authentication_form=TraxAuthenticationForm)
    if request.user.is_authenticated():
        resp.set_cookie('username', request.user.username)
    return resp

def export_tables_as_sheets(request):
    qs = Laptime.objects.all().select_related('track', 'player', 'vehicle')
    column_names = ['pk', 'millis', 'millis_per_km', 'vehicle__name']
    return excel.make_response_from_query_sets(query_sets, column_names, 'xls',
                                               file_name="custom")




def timestamp_dev(request):
    """replacement for the little shell script returning the current datetime
    for the SSR creator."""
    from django.utils.timezone import now
    n = now()
    return HttpResponse('{0:.9f}'.format(n.timestamp()), content_type="text/plain")

website/vehicles/views.py
from django.forms import CheckboxSelectMultiple
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, UpdateView,
                                  DetailView, ListView)

from trax.utils import is_staff_required, ModelFormWidgetMixin
from .models import Vehicle


class VehicleList(ListView):
    model = Vehicle
    template_name = 'vehicles/vehicle_list.html'

    def get_queryset(self):
        through = Vehicle.classes.through
        return through.objects.filter(vehicle__active=True)


class VehicleDetail(DetailView):
    model = Vehicle


@method_decorator(is_staff_required, name='dispatch')
class VehicleCreate(ModelFormWidgetMixin, CreateView):
    model = Vehicle
    fields = ["name", "cc_laptime_millis", "description", "classes",
              "cc_millis_per_km"]
    widgets = {"classes": CheckboxSelectMultiple }
    success_url = reverse_lazy('vehicle_list')


@method_decorator(is_staff_required, name='dispatch')
class VehicleUpdate(ModelFormWidgetMixin, UpdateView):
    model = Vehicle
    fields = ["name", "cc_laptime_millis", "description", "classes",
              "cc_millis_per_km"]
    widgets = {"classes": CheckboxSelectMultiple }
    success_url = reverse_lazy('vehicle_list')

website/trax/templates/trax/homepage.html
{% extends "trax_base.html" %}
{% load i18n %}

{% block title %}Hi {% if not request.user.is_authenticated %}there{% else %}{{ request.user }}{% endif %}!{% endblock %}
{% block content %}
    <div class="col-md-4">
      {% if not request.user.is_authenticated %}
        <h1>Hi there! </h1>
        <p><b>Welcome to gtaracing.net!</b></p>
        <p>Browse through the tracks, marvel at the hottest laps of the users who have signed up here.
          But if you want <b>more</b>, register or login! (there's a clicky-thing on top of this page)</p>

      {% else %}
        <h1>Hi {{ request.user }}!</h1>
      {% endif %}
      <p>This little website aims to be a resource for all kinds of racing activities in GTA online.
        At the moment, there is a list of great <a href="{% url "track_list" %}"><b>tracks</b></a> with the possibility to enter your fastest laps.
        Registered users can also create new tracks.
      </p>
      <p>There's also a list of all land <a href="{% url "vehicle_list" %}"><b>vehicles</b></a> where you can see how other racers performed on various tracks.
      </p>
      <p>Furthermore, there is a <a href="{% url "randomracelist" %}"><b>Random Grid Generator</b></a> available, so if you host an event with
        multiple races, you can make sure that every participant has a fair chance with their
        positions on the starting grid.</p>
      <p><b><em>NEW!</em></b> You can host <b>Staggered Start Races</b>! Open the page of any track
        and click the button "Host a staggered start race". Your drivers can choose any car they like, and I'll
        try to find out when everyone can start, so everyone has an equal chance for winning a race.
        It is based on either Broughy1322's laps around Cutting Coroners GP ("Standard Only"), or your own laps
        that you entered here before ("Photo Finish") or a mixture of both ("Slow Assist"), meaning that drivers
        who are faster than Broughy on CCGP still use the standard Broughy-time and are not "punished" for being
        quick, whereas slower drivers may start a bit earlier to make them be able to still participate
        competitively.</p>
    </div>
    <div class="col-md-8">
      <h1>Some great verified lap times<small> (one per track)</small></h1>

      <table class="table table-striped table-bordered table-condensed">
        <thead>
        <th>{% trans "Track" %}</th>
        <th>{% trans "Driver" %}</th>
        <th>{% trans "Vehicle" %}</th>
        <th class="text-right">{% trans "Time" %}</th>
        </thead>
        <tbody>
        {% for lap in toplaps %}
          <tr>
            <td>
              {% if lap.link %}
                <a href="{{ lap.link }}"
                 title="external link as proof" target="_blank"
                 ><span class="glyphicon glyphicon-{{ lap.linktype }}"></span></a>
              {% endif %}
              <a href="{{ lap.track.get_absolute_url }}">{{ lap.track }}</a>
            </td>
            <td><a href="{{ lap.player.get_absolute_url }}">{{ lap.player }}</a></td>
            <td><a href="{{ lap.vehicle.get_absolute_url }}">{{ lap.vehicle }}</a></td>
            <td class="text-right">{{ lap.duration }}</td>
          </tr>
        {% endfor %}

        </tbody>
      </table>
      <h1>The most recent tracks
        <small class="pull-right">
          <a href="{% url "track_list" %}" class="btn btn-default">
            <span class="glyphicon glyphicon-road" aria-hidden="true"></span>
            View all tracks</a>
        </small>
        <small class="pull-right">
          <a href="{% url "track_add" %}" class="btn btn-default">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            Add a track</a>
        </small>
      </h1>

      <table class="table table-striped table-bordered table-condensed">
        <thead>
        <th>&nbsp;</th>
        <th>{% trans "Title" %}</th>
        <th>{% trans "Author" %}</th>
        <th class="text-right">{% trans "Players" %}</th>
        <th class="text-right">{% trans "length km" %}</th>
        </thead>
        <tbody>
        {% for track in tracks %}
          <tr>
            <td>{{ track.get_platform_display }}</td>
            <td><a href="{{ track.get_absolute_url }}">{{ track.title }}</a>
              {% if track.video %}
                <span class="glyphicon glyphicon-film"></span>
              {% endif %}
              {% if track.image %}
                <span class="glyphicon glyphicon-picture"></span>
              {% endif %}
            </td>
            <td>{{ track.author }}</td>
            <td class="text-right">{{ track.num_players }}</td>
            <td class="text-right">{{ track.route_length }}</td>
          </tr>
        {% endfor %}

        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

website/trax/templates/trax/imprint.html
{% extends "trax_base.html" %}
{% load static %}
{% load i18n %}

{% block title %}Imprint{% endblock %}
{% block content %}

  <div class="row">
    <div class="col-md-6">
      <img src="{% static "imprint.gif" %}">
    </div>
  <div class="col-md-6">
    <h2>Tools and other stuff being used here</h2>
    <ul>
      <li><a href="https://djangoproject.com/" target="_blank">Django</a> by the Django Foundation</li>
      <li><a href="https://jquery.com/" target="_blank">jQuery</a> by The jQuery Foundation</li>
      <li><a href="https://getbootstrap.com/" target="_blank">Bootstrap</a> by Twitter Inc.</li>
      <li><a href="http://typodermicfonts.com/" target="_blank">Pricedown font</a> by Raymond Larabie</li>
      <li><a href="https://github.com/FriendlyBaron/GridCreator" target="_blank">GridCreator</a> by FriendlyBaron</li>
      <li><a href="https://github.com/NodeGuy/ServerDate" target="_blank">ServerDate.js</a> by David Braun</li>
      <li>500 error page image by Dilon Choudhury</li>
      <li>404 error page image by Jon Trillana</li>

    </ul>
  </div>
  </div>
{% endblock %}

website/trax/templates/trax/not_on_this_platform.html
{% extends "trax_base.html" %}
{% load i18n %}

{% block title %}Hi {% if not request.user.is_authenticated %}there{% else %}{{ request.user }}{% endif %}!{% endblock %}
{% block content %}

  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <h1>Sorry...</h1>
      <p>This page is not available for the platform(s) you activated. Turn on the correct platform icon(s) on top of this page if you want to see it.</p>
    </div>
  </div>
{% endblock %}

website/trax/templates/trax/only_for_pc.html
{% extends "trax_base.html" %}
{% load i18n %}

{% block title %}Hi {% if not request.user.is_authenticated %}there{% else %}{{ request.user }}{% endif %}!{% endblock %}
{% block content %}

  <div class="row">
    <div class="col-md-4">
        <h1>Sorry...</h1>
      <p>This page is only available for PC users. Turn on the "PC" icon on top of this page if you want to see it.</p>
    </div>
  </div>
{% endblock %}