website/tracks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from tracks import views

urlpatterns = [
    url(r'^$', views.TrackList.as_view(), name='track_list'),
    url(r'^(?P<pk>\d+)/$', views.track_detail, name='track_detail'),
    url(r'^(?P<track_pk>\d+)/laptimes.json$', views.laptime_json, name='laptime_json'),
    url(r'^tracks.json$', views.tracks_json, name='tracks_json'),
    url(r'^(?P<lap_pk>\d+)/add_laptime/$', views.laptime_add, name='laptime_add'),
    url(r'^l/(?P<lap_pk>\d+)/delete/$', views.laptime_delete, name='laptime_delete'),
    url(r'^add/$', views.TrackCreate.as_view(), name='track_add'),
    url(r'^(?P<pk>\d+)/edit/$', views.TrackEdit.as_view(), name='track_edit'),
]

website/trax/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
# from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from . import views
from tracks import views as tracks_views


urlpatterns = [
#    url(r'^admin/', admin.site.urls),
    url(r'^t/', include('tracks.urls')),
    url(r'^v/', include('vehicles.urls')),
    url(r'^r/', include('randomizer.urls')),
    url(r'^e/', include('events.urls')),
    url(r'^p/', include('players.urls')),
    # url(r'^$', cache_page(60*10)(views.Homepage.as_view()), name="homepage"),
    url(r'^$', views.Homepage.as_view(), name="homepage"),
    url(r'^accounts/login/$', views.login_view, name="login"),
    url(r'^accounts/logout/$', views.logout_view, name="logout"),
    url(r'^accounts/register/$', views.Registration.as_view(), name="register"),
    url(r'^imprint/$', TemplateView.as_view(template_name='trax/imprint.html'),
        name="imprint"),
    url(r'^robots.txt$', TemplateView.as_view(template_name='trax/imprint.html'),
                      name="DEVELOPMENTrobots.txt"),
    url(r'^miniutil/now$', views.timestamp_dev, name="DEVELOPMENTnow"),
    url(r'^epsilon/$', tracks_views.epsilon_detail, name="epsilon_detail"),
#    url(r'^grotti17/$', tracks_views.grotti17_detail, name="grotti17_detail"),
    url(r'^unaffordable/$', tracks_views.unaffordable_detail,
        name="unaffordable_detail"),
    url(r'^tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/tracks/models.py
from urllib.parse import urlparse
from easy_thumbnails.fields import ThumbnailerImageField
from threadlocals.threadlocals import get_current_request
from trax.choices import GAME_MODES, ROUTE_TYPES, PLATFORM_CHOICES
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from embed_video.fields import EmbedVideoField

from trax.utils import get_object_by_string


class TrackQueryset(models.query.QuerySet):
    def my(self):
        request = get_current_request()
        if request and request.user.is_authenticated():
            return self.filter(creator=request.user)
        return self.all()


class TrackManager(models.Manager):
    def get_queryset(self):
        default_platforms = 'pc ps4 xb1'
        qs = TrackQueryset(self.model, using=self._db)
        request = get_current_request()
        if request:
            platforms = request.COOKIES.get('traxpf', default_platforms)
            platforms = platforms.replace("%20", " ").split()
            if not platforms:
                platforms = default_platforms.split()
            qs = qs.filter(platform__in=platforms)
        return qs

    def my(self):
        return self.get_queryset().my()


class Track(models.Model):
    objects = TrackManager()

    title = models.CharField(unique=True, max_length=256)
    description = models.TextField(blank=True, default='')
    author = models.CharField(max_length=64, default='', null=False)
    creator = models.ForeignKey("players.Player", null=True)
    link = models.URLField(null=True)
    video = EmbedVideoField(null=True, blank=True)
    game_mode = models.CharField(max_length=8, choices=GAME_MODES,
                                 default=GAME_MODES[0][0])
    route_type = models.CharField(max_length=1, choices=ROUTE_TYPES,
                                  default=ROUTE_TYPES[0][0])
    route_length_km = models.FloatField(null=True)
    num_players = models.PositiveSmallIntegerField(null=True)
    typical_laptime = models.IntegerField(
        help_text=_('How many seconds does it typically take for a fully '
                    'customized car to finish a lap with no major issues?'),
        null=True)
    pit_lane = models.BooleanField(
        help_text=_('Does the track have a pit lane with repair icons?'),
        default=False)
    surface_street = models.SmallIntegerField(
        help_text=_('Typical streets in Los Santos'), default=0)
    surface_road = models.SmallIntegerField(
        help_text=_('Tarmac roads e.g. Blaine County'), default=0)
    surface_dirt = models.SmallIntegerField(
        help_text=_('Non-tarmac dirt roads e.g. in Sandy Shores'), default=0)
    surface_flat = models.SmallIntegerField(
        help_text=_('Tarmac and concrete surface at LS airport, Fort '
                    'Zancudo and similar areas. Highways as well.'), default=0)
    surface_stunt = models.SmallIntegerField(
        help_text=_('Surfaces made with stunt props.'), default=0)
    surface_offroad = models.SmallIntegerField(
        help_text=_('Anything offroad e.g. forests, fields, grasslands, '
                    'desert'), default=0)
    elevation_changes = models.SmallIntegerField(
        help_text=_("From airport-flat (0), to Tongva Hills (50) to "
                    "rollercoastery ups and downs (100)."),
        default=0)
    car_classes = models.ManyToManyField('vehicles.VehicleClass')
    platform = models.CharField(max_length=8,
                                choices=PLATFORM_CHOICES, default='pc')
    reference_track = models.BooleanField(
        default=False, help_text=_("Is this a reference track for laptimes?"))
    image = ThumbnailerImageField(upload_to='trackimages', blank=True)
    num_hairpins = models.SmallIntegerField(default=0)
    num_slow_turns = models.SmallIntegerField(default=0)
    num_fast_turns = models.SmallIntegerField(default=0)
    num_slow_chicanes = models.SmallIntegerField(default=0)
    num_fast_chicanes = models.SmallIntegerField(default=0)
    include_in_halloffame = models.BooleanField(default=True)

    @property
    def terrains(self):
        return [
            {'type': _('Street'), 'perc': self.surface_street, 'class': 'st'},
            {'type': _('Road'), 'perc': self.surface_road, 'class': 'ro'},
            {'type': _('Dirt'), 'perc': self.surface_dirt, 'class': 'di'},
            {'type': _('Flat'), 'perc': self.surface_flat, 'class': 'fl'},
            {'type': _('Stunt'), 'perc': self.surface_stunt, 'class': 's'},
            {'type': _('Offroad'), 'perc': self.surface_offroad, 'class': 'of'},
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('track_detail', args=[str(self.pk)])

    @property
    def duration(self):
        minu, seco = divmod(self.typical_laptime, 60)
        return "{0}:{1:02}".format(int(minu), int(seco))

    @property
    def route_length(self, unit='km'):
        return "{:.02f}".format(self.route_length_km)


def get_track_by_string(s):
    """returns a track object, if something with a score > 70 could be found."""
    return get_object_by_string(s, Track, 'title')


class Laptime(models.Model):
    track = models.ForeignKey("tracks.Track")
    player = models.ForeignKey("players.Player")
    created = models.DateTimeField(auto_now_add=True)
    recorded = models.DateField(null=True)
    vehicle = models.ForeignKey("vehicles.Vehicle")
    millis = models.IntegerField(default=0)
    millis_per_km = models.IntegerField(default=0)
    comment = models.TextField(default='', null=True, blank=True)
    video = EmbedVideoField(null=True)
    link = models.URLField(null=True)
    pc_60fps = models.BooleanField(default=False)

    class Meta:
        ordering=['-pk', ]

    def __str__(self):
        return '{0} {1}'.format(self.player.username,
                                self.vehicle.name)

    @property
    def duration(self):
        seco, mill = divmod(self.millis, 1000)
        minu, seco = divmod(seco, 60)
        return "{0}:{1:02}.{2:03}".format(int(minu), int(seco), int(mill))


    @property
    def km_per_h(self):
        if self.millis_per_km != 0:
            return '{:.3f}'.format(
                (1.0 / self.millis_per_km ) * 1000 * 3600
            )
        return '?'

    @property
    def linktype(self):
        """returns "l" for generic link, "v" for videolink, "" if no link at all"""
        hostname = urlparse(self.link).hostname
        VIDEOSITES = ('vimeo', 'youtu', 'dailymotio', 'twitch')
        if not hostname:
            return ""
        for hostpart in VIDEOSITES:
            if hostname.startswith(hostpart) or '.' + hostpart in hostname:
                return "film"
        return "link"

website/tracks/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField, \
    CheckboxSelectMultiple

from easy_thumbnails.widgets import ImageClearableFileInput
from events.models import StaggeredStartRace
from vehicles.models import VehicleClass
from .models import Track, Laptime


class TrackForm(ModelForm):
    car_classes = ModelMultipleChoiceField(widget=CheckboxSelectMultiple,
                                           required=True, queryset=VehicleClass.objects.all(),
                                           )
    class Meta:
        model = Track
        fields = [
            'title', 'description', 'author', 'link', 'video', 'game_mode',
            'route_type', 'route_length_km', 'num_players', 'typical_laptime',
            'pit_lane', 'surface_street', 'surface_road',
            'surface_dirt', 'surface_flat', 'surface_stunt', 'surface_offroad',
            'elevation_changes', 'car_classes', 'platform',
            'image', 'num_hairpins', 'num_slow_turns', 'num_fast_turns',
            'num_slow_chicanes', 'num_fast_chicanes'
        ]
        widgets = {
            'image': ImageClearableFileInput(),
        }



class SSRCreateForm(ModelForm):
    class Meta:
        model = StaggeredStartRace
        fields = ["vehicle_class", "algorithm", "laps", "track", "comment"]

website/tracks/templates/tracks/add_grotti17_form.html
{% load i18n %}{% load widget_tweaks %}
<div class="panel panel-default">
  <div class="panel-heading"><h3 class="pricedown" style="margin-top:0px;margin-bottom:0px;">Add your own lap time here</h3></div>

  {% if request.user.is_authenticated %}

    <form action="{% url "laptime_add" obj.pk %}" method="POST">
      <div class="panel-body">
        {% csrf_token %}
        <label>Vehicle</label><input type="hidden" name="vehicle" value="451"> <input class="form-control" disabled value="X80 Proto">
        <div>
          <label for="seconds">
            {% trans "lap time" %}
          </label>
          <input name="seconds"
                 required
                 pattern="^\d{1,2}:\d{1,2}\.\d\d?\d?$"
                 id="seconds"
                 title="e.g. '1:03.123'"
                 alt="alttext"
                 type="text">(MM:SS.milli)
        </div>
        <div>
          <label for="recorded">
            {% trans "recorded" %}
          </label>
          <input name="recorded"
                 value="{{ form.recorded.value }}"
                 required
                 pattern="^\d{4}-\d{1,2}-\d{1,2}$"
                 id="recorded"
                 title="e.g. '2016-12-24'"
                 type="text">(YYYY-MM-DD)
        </div>
        <div>
          <label for="id_comment">
            {% trans "comment" %}<small> (optional)</small>
          </label>{% render_field form.comment rows="2" class="form-control"%}
        </div>
        <div>
          <label for="id_anylink">
            Mandatory link to prove your lap time
          </label>{% render_field form.anylink class="form-control"%}
        </div>
      </div>
      <div class="panel-footer">
        <button class="btn btn-primary" type="submit">Add this lap time</button>
      </div>
    </form>

  {% else %}

    <div style="padding:1em">
      <span class="glyphicon glyphicon-info-sign" style="font-size:18px;" aria-hidden="true"></span>
      You need to log in first. Click "Login/Register" on top of this page.
    </div>
    <div class="panel-footer">
      &nbsp;
    </div>

  {% endif %}
</div>

website/tracks/templates/tracks/add_laptime_form.html
{% load i18n %}{% load widget_tweaks %}
<div class="panel panel-default">
  <div class="panel-heading"><h3 class="pricedown" style="margin-top:0px;margin-bottom:0px;">Add your own lap time here</h3></div>

  {% if request.user.is_authenticated %}

    <form action="{% url "laptime_add" obj.pk %}" method="POST">
      <div class="panel-body">
        {% csrf_token %}
        {% render_field form.vehicle class="combobox form-control" %}
        <div>
          <label for="seconds">
            {% trans "lap time" %}
          </label>
          <input name="seconds"
                 required
                 pattern="^\d{1,2}:\d{1,2}\.\d\d?\d?$"
                 id="seconds"
                 title="e.g. '1:03.123'"
                 alt="alttext"
                 type="text">(MM:SS.milli)
        </div>
        <div>
          <label for="recorded">
            {% trans "recorded" %}
          </label>
          <input name="recorded"
                 value="{{ form.recorded.value }}"
                 required
                 pattern="^\d{4}-\d{1,2}-\d{1,2}$"
                 id="recorded"
                 title="e.g. '2016-12-24'"
                 type="text">(YYYY-MM-DD)
        </div>
        <div>
          <label for="id_comment">
            {% trans "comment" %}<small> (optional)</small>
          </label>{% render_field form.comment rows="2" class="form-control"%}
        </div>
        <div>
          <label for="id_anylink">
            {% trans "link" %}<small> (optional) to prove your great laptime</small>
          </label>{% render_field form.anylink class="form-control"%}
        </div>
      </div>
      <div class="panel-footer">
        <button class="btn btn-primary" type="submit">Add this lap time</button>
      </div>
    </form>

  {% else %}

    <div style="padding:1em">
      <span class="glyphicon glyphicon-info-sign" style="font-size:18px;" aria-hidden="true"></span>
      You need to log in first. Click "Login/Register" on top of this page.
    </div>
    <div class="panel-footer">
      &nbsp;
    </div>

  {% endif %}
</div>

website/tracks/templates/tracks/add_unaffordable_form.html
{% load i18n %}{% load widget_tweaks %}
<div class="panel panel-default">
  <div class="panel-heading"><h3 class="pricedown" style="margin-top:0px;margin-bottom:0px;">Add your own lap time here</h3></div>

  {% if request.user.is_authenticated %}

    <form action="{% url "laptime_add" obj.pk %}" method="POST">
      <div class="panel-body">
        {% csrf_token %}
        {% render_field form.vehicle class="combobox form-control" %}
        <div>
          <label for="seconds">
            {% trans "lap time" %}
          </label>
          <input name="seconds"
                 required
                 pattern="^\d{1,2}:\d{1,2}\.\d\d?\d?$"
                 id="seconds"
                 title="e.g. '1:03.123'"
                 alt="alttext"
                 type="text">(MM:SS.milli)
        </div>
        <div>
          <label for="recorded">
            {% trans "recorded" %}
          </label>
          <input name="recorded"
                 value="{{ form.recorded.value }}"
                 required
                 pattern="^\d{4}-\d{1,2}-\d{1,2}$"
                 id="recorded"
                 title="e.g. '2016-12-24'"
                 type="text">(YYYY-MM-DD)
        </div>
        <div>
          <label for="id_comment">
            {% trans "comment" %}<small> (optional)</small>
          </label>{% render_field form.comment rows="2" class="form-control"%}
        </div>
        <div>
          <label for="id_anylink">
            Mandatory link to prove your lap time
          </label>{% render_field form.anylink class="form-control"%}
        </div>
      </div>
      <div class="panel-footer">
        <button class="btn btn-primary" type="submit">Add this lap time</button>
      </div>
    </form>

  {% else %}

    <div style="padding:1em">
      <span class="glyphicon glyphicon-info-sign" style="font-size:18px;" aria-hidden="true"></span>
      You need to log in first. Click "Login/Register" on top of this page.
    </div>
    <div class="panel-footer">
      &nbsp;
    </div>

  {% endif %}
</div>

website/tracks/templates/tracks/track_base.html
{% extends "base.html" %}{% block menu_tracks_active %}active{% endblock %}

website/tracks/templates/tracks/track_detail.html
{% extends "tracks/track_base.html" %}
{% load static %}
{% load thumbnail %}
{% load bootstrap3 %}
{% load embed_video_tags %}{% load i18n %}
{% load trax_extras %}

{% block title %}{{ obj.title }}{% endblock %}
{% block content %}

  {% include "tracks/ssrcreator_dialog.html" %}
  <div class="row">
  <div class="col-md-12">
    <h1>
      {{ obj.title }} <small>[{{ obj.get_platform_display }}] by {{ obj.author }}</small>

      {% if request.user.is_authenticated %}
      {% if can_edit %}
      <small class="pull-right">
        <a href="{% url "track_edit" obj.pk %}" class="btn btn-default">
          <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
          Edit</a>
      </small>
        {% endif %}
      <small class="pull-right">
      <a href="#ssrcreator" role="button"
         class="btn btn-default"
         data-toggle="modal">
        <span class="glyphicon glyphicon-road" aria-hidden="true"></span>
        Host a staggered start race…</a>
      </small>
      {% endif %}

    </h1>
  </div>

  </div>
  <div class="row">
    <div class="col-md-4 ">
      {% if obj.image %}
        <a href="/media/{{ obj.image }}" target="_blank">
        <img src="{% thumbnail obj.image 320x200 crop %}" style="width:100%" alt="">
        </a>
        <h3 class="pricedown">Description</h3>
        {% else %}
      <h3 class="pricedown" style="padding-top:0;margin-top:0">Description</h3>
      {% endif %}
      {% if obj.description %}
        <p>{{ obj.description|urlizetrunc:25|url_target_blank }}</p>
      {% else %}
        <p>This track has no description. Maybe you'd like to add one?</p>
      {% endif %}
    {% if obj.description and obj.image %}{% else %}
      <h3 class="pricedown">Video</h3>
      {% if obj.video %}
        <div class="text-right">{% video obj.video '320x200' is_secure=True %}</div>
      {% else %}
        <p>This track has no video. Maybe you'd like to add one? Send a <a href="https://socialclub.rockstargames.com/member/abe.cede/" target="_blank">message to Abe.Cede via Socialclub</a> with a video URL.</p>
      {% endif %}
    {% endif %}
    </div>
    <div class="col-md-4">
      {% if obj.description and obj.image %}
        <h3 class="pricedown" style="padding-top:0;margin-top:0">Video</h3>
        {% if obj.video %}
          <div class="text-right">{% video obj.video '320x200' is_secure=True %}</div>
        {% else %}
          <p>This track has no video. Maybe you'd like to add one? Send a <a href="https://socialclub.rockstargames.com/member/abe.cede/" target="_blank">message to Abe.Cede via Socialclub</a> with a video URL.</p>
        {% endif %}
      {% endif %}
      <h3 class="pricedown" style="padding-top:0;margin-top:0">Surface
        <small>(move mouse over the colors to see the terrain type and percentage)</small></h3>
      <div class="progress">
        {% for terrain in obj.terrains %}
          <div
              data-toggle="tooltip"
              title="{{ terrain.perc }}% {{ terrain.type }}"
              class="progress-bar terrain_{{ terrain.class }}"
              style="width: {{ terrain.perc }}%">
          </div>
        {% endfor %}
      </div>
      <dl class="dl-horizontal">
        <dt>{% trans "game mode" %}</dt><dd>{{ obj.get_game_mode_display }}</dd>
        <dt>{% trans "route type" %}</dt><dd>{{ obj.get_route_type_display }}</dd>
        <dt>{% trans "route length" %}</dt><dd>{{ obj.route_length }} km</dd>
        <dt>{% trans "num players" %}</dt><dd>{{ obj.num_players }}</dd>
        <dt>{% trans "typical lap time" %}</dt><dd>{{ obj.duration }}</dd>
        <dt>{% trans "pit lane" %}</dt><dd>{% if not obj.pit_lane %}NOT {% endif %}available</dd>
        <dt>{% trans "RSC link" %}</dt><dd>{{ obj.link|urlizetrunc:25|url_target_blank }}</dd>
        <dt>{% trans "classes" %}</dt>
        <dd>{% for foo in obj.car_classes.all %}{{  foo }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
        </dd>
        <dt>{% trans "elevation changes" %}</dt><dd>{{ obj.elevation_changes }}</dd>
        <dt>{% trans "maintainer" %}</dt><dd>{{ obj.creator }}</dd>
      </dl>
    </div>
    <div class="col-md-4">{% include "tracks/add_laptime_form.html" %}</div>
  </div>
  {% include "tracks/laptime_table.html" %}
{% endblock %}

website/tracks/templates/tracks/track_form.html
{% extends "tracks/track_base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% if form.instance.pk %}Edit track
  "{{ form.instance.title }}"{% else %}Add a new track{% endif %}{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-md-12">
      <h1>
        {% if form.instance.pk %}
          Edit track "{{ form.instance.title }}"
        {% else %}
          Add a new track
        {% endif %}
      </h1></div></div>

  {% if form.errors %}
    {{ form.errors }}

  {% endif %}

  <div class="row">
    <form action="." method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="col-md-6">
        <dl class="dl-horizontal">
          <dt><label for="id_title">Title</label></dt>
          <dd>{% render_field form.title class="form-control" %}
            {{ form.title.help_text }}</dd>
          <dt><label for="id_game_mode">Game mode</label></dt>
          <dd>{% render_field form.game_mode class="form-control" %}
            {{ form.game_mode.help_text }}</dd>
          <dt><label for="id_route_type">Route type</label></dt>
          <dd>{% render_field form.route_type class="form-control" %}
            {{ form.route_type.help_text }}</dd>
          <dt><label for="id_route_length">Route length (in km)</label></dt>
          <dd>{% render_field form.route_length_km class="form-control" %}
            {{ form.route_length_km.help_text }}</dd>
          <dt><label for="id_num_players">Number of players</label></dt>
          <dd>{% render_field form.num_players class="form-control" %}
            {{ form.num_players.help_text }}</dd>
          <dt><label for="id_typical_laptime">Typical laptime</label></dt>
          <dd>{% render_field form.typical_laptime class="form-control" %}
            {{ form.typical_laptime.help_text }}</dd>
          <dt><label for="id_description">Description</label></dt>
          <dd>{% render_field form.description class="form-control" %}
            {{ form.description.help_text }}</dd>
          <dt><label for="id_link">RSC Link</label></dt>
          <dd>{% render_field form.link class="form-control" %}
            {{ form.link.help_text }}</dd>
          <dt><label for="id_video">Showcase video</label></dt>
          <dd>{% render_field form.video class="form-control" %}
            {{ form.video.help_text }}</dd>
          <dt><hr><label for="id_image">Image</label></dt>
          <dd><hr>{{ form.image }}
            {{ form.image.help_text }}</dd>
        </dl>
        <div class="row">
          <div class="col-md-12">
            Surfaces (the values MUST have a sum of 100)
          </div>
          <div class="col-md-2">Street
            {% render_field form.surface_street class="form-control" title="Typical streets in the city" %}
          </div>
          <div class="col-md-2">Roads
            {% render_field form.surface_road class="form-control" title="Tarmac roads e.g. Route 68" %}
          </div>
          <div class="col-md-2">Dirt
            {% render_field form.surface_dirt class="form-control" title="Non-tarmac gravel roads like in the desert" %}
          </div>
          <div class="col-md-2">Flat/Hwy
            {% render_field form.surface_flat class="form-control" title="Highways and flat areas like on LS Airport and Zancudo" %}
          </div>
          <div class="col-md-2">Stunt
            {% render_field form.surface_stunt class="form-control" title="Any artifical surface like stunt props." %}
          </div>
          <div class="col-md-2">Offroad
            {% render_field form.surface_offroad class="form-control" title="Grass, fields, forests etc." %}
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <dl class="dl-horizontal">
          <dt><label for="id_author">Author</label></dt>
          <dd>{% render_field form.author class="form-control" %}
            {{ form.author.help_text }}</dd>
          <dt><label for="id_platform">Platform</label></dt>
          <dd>{% render_field form.platform class="form-control" %}
            {{ form.platform.help_text }}</dd>
          <dt><label for="id_elevation_changes">Elevation changes</label></dt>
          <dd>{% render_field form.elevation_changes class="form-control" %}
            {{ form.elevation_changes.help_text }}</dd>
        </dl>
        <hr>
        <dl>
          <dt>Characteristics</dt>
          <dd>Enter the number of turns/corners of the track below. (not mandatory, but very much appreciated)</dd>
        </dl>
        <dl class="dl-horizontal">
          <dt><label for="id_num_hairpins">hairpin turns</label></dt>
          <dd>{% render_field form.num_hairpins class="form-control" %}
            {{ form.num_hairpins.help_text }}</dd>
          <dt><label for="id_num_slow_turns">low speed turns</label></dt>
          <dd>{% render_field form.num_slow_turns class="form-control" %}
            {{ form.num_slow_turns.help_text }}</dd>
          <dt><label for="id_num_fast_turns">high speed turns</label></dt>
          <dd>{% render_field form.num_fast_turns class="form-control" %}
            {{ form.num_fast_turns.help_text }}</dd>
          <dt><label for="id_num_slow_chicanes">slow speed chicanes</label></dt>
          <dd>{% render_field form.num_slow_chicanes class="form-control" %}
            {{ form.num_slow_chicanes.help_text }}</dd>
          <dt><label for="id_num_fast_chicanes">high speed chicanes</label></dt>
          <dd>{% render_field form.num_fast_chicanes class="form-control" %}
            {{ form.num_fast_chicanes.help_text }}</dd>
        </dl>
        <hr>
        <dl class="dl-horizontal">
          <dt><label for="id_car_classes">Car classes</label></dt>
          <dd>{% render_field form.car_classes class="form-control" %}
            {{ form.car_classes.help_text }}</dd>
          <dt><label for="id_pit_lane">Pit lane available?</label></dt>
          <dd>{% render_field form.pit_lane class="form-control" %}
            {{ form.pit_lane.help_text }}</dd>
        </dl>
      </div>
      <div class="row">
        <div class="col-md-12">
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}