website/players/urls.py
from django.conf.urls import url
from .views import PlayerDetail, PlayerList, change_password

urlpatterns = [
    url(r'^$', PlayerList.as_view(),
        name='player_list'),
    url(r'^(?P<pk>\d+)/$', PlayerDetail.as_view(),
        name='player_detail'),
    url(r'^pw/(?P<hash>.+)/$', change_password,
        name='password_changer'),
]

website/trax/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
# from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from . import views
from tracks import views as tracks_views


urlpatterns = [
#    url(r'^admin/', admin.site.urls),
    url(r'^t/', include('tracks.urls')),
    url(r'^v/', include('vehicles.urls')),
    url(r'^r/', include('randomizer.urls')),
    url(r'^e/', include('events.urls')),
    url(r'^p/', include('players.urls')),
    # url(r'^$', cache_page(60*10)(views.Homepage.as_view()), name="homepage"),
    url(r'^$', views.Homepage.as_view(), name="homepage"),
    url(r'^accounts/login/$', views.login_view, name="login"),
    url(r'^accounts/logout/$', views.logout_view, name="logout"),
    url(r'^accounts/register/$', views.Registration.as_view(), name="register"),
    url(r'^imprint/$', TemplateView.as_view(template_name='trax/imprint.html'),
        name="imprint"),
    url(r'^robots.txt$', TemplateView.as_view(template_name='trax/imprint.html'),
                      name="DEVELOPMENTrobots.txt"),
    url(r'^miniutil/now$', views.timestamp_dev, name="DEVELOPMENTnow"),
    url(r'^epsilon/$', tracks_views.epsilon_detail, name="epsilon_detail"),
#    url(r'^grotti17/$', tracks_views.grotti17_detail, name="grotti17_detail"),
    url(r'^unaffordable/$', tracks_views.unaffordable_detail,
        name="unaffordable_detail"),
    url(r'^tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/events/models.py
import datetime
import json
import os

import bleach
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
# from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _

from trax.choices import RACE_STATES, SSR_ALGORITHMS, PITLOGENTRIES

#class StaggeredPlaylist(models.Model):
#    title = models.CharField(max_length=256)
#    creator = models.ForeignKey('players.Player')
#    created = models.DateTimeField(auto_now_add=True)
#    platform = models.CharField(max_length=8,
#                                choices=PLATFORM_CHOICES, default='pc')


class StaggeredStartRace(models.Model):
    track = models.ForeignKey('tracks.Track')
    vehicle_class = models.ForeignKey('vehicles.VehicleClass', null=True)
    laps = models.PositiveSmallIntegerField(default=5)
    host = models.ForeignKey('players.Player')
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=RACE_STATES.choices,
                              default=RACE_STATES.planning)
    hosting_date = models.DateTimeField(null=True)
    link = models.URLField(
        null=True, help_text=_("could be a screenshot URL of the results"))
    comment = models.TextField(default="", blank=True)
    start_timestamp = models.DateTimeField(null=True, default=None)
    per_overtake_deficit_millis = models.IntegerField(null=True, default=600)
#    staggeredplaylist = models.ForeignKey('StaggeredPlaylist', null=True)
#    number_in_playlist = models.PositiveSmallIntegerField(default=0)
    algorithm = models.CharField(max_length=2, choices=SSR_ALGORITHMS,
                                 default='SO')

    def __str__(self):
        hosting_date = self.hosting_date and \
                       self.hosting_date.strftime('%Y-%m-%d') or \
                       'not defined'
        return '{0} by {1} ({2})'.format(
            self.track.title, self.host.username,
            hosting_date)

    def get_absolute_url(self):
        return reverse_lazy('staggeredstartrace_detail',
                            kwargs={'pk': self.pk})

    @property
    def json_url(self):
        return os.path.join(
            settings.STATIC_URL, 'ssr',
            '{0}.json'.format(self.pk))

    def update_json(self):
        """saves the current whole json state for faster access"""
        players = []
        current_index = -1
        already_seen_a_vehicle = False
        racetime = 0
        qset = self.ssrparticipation_set.all()

        # in case some players did not choose a car,
        # we need to ignore them when racing starts
        if self.status == RACE_STATES.running:
            qset = qset.exclude(estimated_laptime__isnull=True)

        for s in qset.order_by('-estimated_laptime'):
            current_index += 1
            estimated_laptime = 0
            if s.estimated_laptime:
                estimated_laptime = s.estimated_laptime
            if not already_seen_a_vehicle and estimated_laptime:
                already_seen_a_vehicle = True
                racetime = estimated_laptime * self.laps
            start_after_first = datetime.timedelta(
                milliseconds=racetime - (estimated_laptime * self.laps))
            minutes = int(start_after_first.seconds / 60)
            seconds = int(start_after_first.seconds % 60)
            millis = int(start_after_first.microseconds / 1000)
            startafterstr = '{0:02d}:{1:02d}.{2:03d}'.format(
                minutes, seconds, millis)
            newdict = {'username': s.player.username,
                            'pk': s.player.pk,
                            'vehicle': s.vehicle and s.vehicle.name or '',
                            'estimated_laptime': estimated_laptime,
                            'start_after_first': startafterstr,
                            }
            if s.start_timestamp:
                newdict['timestamp'] = int(s.start_timestamp.timestamp()*1000)
            players.append(newdict)
        dct = {'status': self.status, 'players': players}
        filename = os.path.join(
            settings.STATIC_ROOT, 'ssr',
            '{0}.json'.format(self.pk))
        with open(filename, 'w') as f:
            f.write(json.dumps({'data': dct}, separators=(',', ':')))


class SSRParticipation(models.Model):
    player = models.ForeignKey("players.Player")
    vehicle = models.ForeignKey("vehicles.Vehicle", null=True, blank=True)
    staggeredstartrace = models.ForeignKey('StaggeredStartRace')
    estimated_laptime = models.IntegerField(
        null=True, help_text='according to calculations the estimated '
                             'total racing net time for one lap.')
    laptime = models.ForeignKey("tracks.Laptime", null=True)
    start_timestamp = models.DateTimeField(null=True)

    class Meta:
        ordering = ('start_timestamp', 'player__username')

    @property
    def start_in_millis(self):
        tdobj = self.start_timestamp - datetime.datetime.now(
            tz=self.start_timestamp.tzinfo)
        return int(tdobj.total_seconds() * 1000)


class PitAssistant(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField(default='', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=RACE_STATES.choices,
                              default=RACE_STATES.planning)
    pitstop_seconds = models.PositiveSmallIntegerField(default=30)
    start_timestamp = models.DateTimeField(null=True)
    owner = models.ForeignKey("players.Player", null=True)

    def get_absolute_url(self):
        return reverse_lazy('pita_detail',
                            kwargs={'pk': self.pk})

    @property
    def json_root(self):
        return os.path.join(
            settings.STATIC_URL, 'pitassistant',
            '{0}/'.format(self.pk))


class PitAParticipation(models.Model):
    player = models.ForeignKey("players.Player")
    pitassistant = models.ForeignKey('events.PitAssistant')


class PitLogEntry(models.Model):
    pitassistant = models.ForeignKey('events.PitAssistant')
    ingameseconds_created = models.IntegerField()
    text = models.CharField(max_length=1024, default='', blank=True)
    entrytype = models.CharField(max_length=1, choices=PITLOGENTRIES.choices,
                                 default=PITLOGENTRIES.pitstop)
    for_player = models.ForeignKey("players.Player", null=True)


class Hotlapping(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField(default='', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey("players.Player", null=True)
    track = models.ForeignKey("tracks.Track")
    vehicles = models.ManyToManyField(to="vehicles.Vehicle",
                                      related_name="vehicles", )
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    closing_text = models.TextField(default='', blank=True)
    divisions_text = models.TextField(default='10:Top Ten\n20:Rest of the starting grid\n999:Not fast enough')
    entries = models.ManyToManyField("tracks.Laptime",
                                     through="HotlappingLaptime",
                                     through_fields=('hotlapping', 'laptime')
                                     )
    time_period_text = models.CharField(default='', blank=True,
                                        max_length=256)
    webhook_url = models.URLField(null=True)

    class Meta:
        ordering = ('-end_date', 'pk')

    def get_absolute_url(self):
        return reverse_lazy('hl_detail',
                            kwargs={'pk': self.pk})


class HotlappingLaptime(models.Model):
    approved = models.BooleanField(default=False)
    hotlapping = models.ForeignKey("events.Hotlapping", on_delete=models.CASCADE)
    laptime = models.ForeignKey("tracks.Laptime", on_delete=models.CASCADE)

website/tracks/models.py
from urllib.parse import urlparse
from easy_thumbnails.fields import ThumbnailerImageField
from threadlocals.threadlocals import get_current_request
from trax.choices import GAME_MODES, ROUTE_TYPES, PLATFORM_CHOICES
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from embed_video.fields import EmbedVideoField

from trax.utils import get_object_by_string


class TrackQueryset(models.query.QuerySet):
    def my(self):
        request = get_current_request()
        if request and request.user.is_authenticated():
            return self.filter(creator=request.user)
        return self.all()


class TrackManager(models.Manager):
    def get_queryset(self):
        default_platforms = 'pc ps4 xb1'
        qs = TrackQueryset(self.model, using=self._db)
        request = get_current_request()
        if request:
            platforms = request.COOKIES.get('traxpf', default_platforms)
            platforms = platforms.replace("%20", " ").split()
            if not platforms:
                platforms = default_platforms.split()
            qs = qs.filter(platform__in=platforms)
        return qs

    def my(self):
        return self.get_queryset().my()


class Track(models.Model):
    objects = TrackManager()

    title = models.CharField(unique=True, max_length=256)
    description = models.TextField(blank=True, default='')
    author = models.CharField(max_length=64, default='', null=False)
    creator = models.ForeignKey("players.Player", null=True)
    link = models.URLField(null=True)
    video = EmbedVideoField(null=True, blank=True)
    game_mode = models.CharField(max_length=8, choices=GAME_MODES,
                                 default=GAME_MODES[0][0])
    route_type = models.CharField(max_length=1, choices=ROUTE_TYPES,
                                  default=ROUTE_TYPES[0][0])
    route_length_km = models.FloatField(null=True)
    num_players = models.PositiveSmallIntegerField(null=True)
    typical_laptime = models.IntegerField(
        help_text=_('How many seconds does it typically take for a fully '
                    'customized car to finish a lap with no major issues?'),
        null=True)
    pit_lane = models.BooleanField(
        help_text=_('Does the track have a pit lane with repair icons?'),
        default=False)
    surface_street = models.SmallIntegerField(
        help_text=_('Typical streets in Los Santos'), default=0)
    surface_road = models.SmallIntegerField(
        help_text=_('Tarmac roads e.g. Blaine County'), default=0)
    surface_dirt = models.SmallIntegerField(
        help_text=_('Non-tarmac dirt roads e.g. in Sandy Shores'), default=0)
    surface_flat = models.SmallIntegerField(
        help_text=_('Tarmac and concrete surface at LS airport, Fort '
                    'Zancudo and similar areas. Highways as well.'), default=0)
    surface_stunt = models.SmallIntegerField(
        help_text=_('Surfaces made with stunt props.'), default=0)
    surface_offroad = models.SmallIntegerField(
        help_text=_('Anything offroad e.g. forests, fields, grasslands, '
                    'desert'), default=0)
    elevation_changes = models.SmallIntegerField(
        help_text=_("From airport-flat (0), to Tongva Hills (50) to "
                    "rollercoastery ups and downs (100)."),
        default=0)
    car_classes = models.ManyToManyField('vehicles.VehicleClass')
    platform = models.CharField(max_length=8,
                                choices=PLATFORM_CHOICES, default='pc')
    reference_track = models.BooleanField(
        default=False, help_text=_("Is this a reference track for laptimes?"))
    image = ThumbnailerImageField(upload_to='trackimages', blank=True)
    num_hairpins = models.SmallIntegerField(default=0)
    num_slow_turns = models.SmallIntegerField(default=0)
    num_fast_turns = models.SmallIntegerField(default=0)
    num_slow_chicanes = models.SmallIntegerField(default=0)
    num_fast_chicanes = models.SmallIntegerField(default=0)
    include_in_halloffame = models.BooleanField(default=True)

    @property
    def terrains(self):
        return [
            {'type': _('Street'), 'perc': self.surface_street, 'class': 'st'},
            {'type': _('Road'), 'perc': self.surface_road, 'class': 'ro'},
            {'type': _('Dirt'), 'perc': self.surface_dirt, 'class': 'di'},
            {'type': _('Flat'), 'perc': self.surface_flat, 'class': 'fl'},
            {'type': _('Stunt'), 'perc': self.surface_stunt, 'class': 's'},
            {'type': _('Offroad'), 'perc': self.surface_offroad, 'class': 'of'},
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('track_detail', args=[str(self.pk)])

    @property
    def duration(self):
        minu, seco = divmod(self.typical_laptime, 60)
        return "{0}:{1:02}".format(int(minu), int(seco))

    @property
    def route_length(self, unit='km'):
        return "{:.02f}".format(self.route_length_km)


def get_track_by_string(s):
    """returns a track object, if something with a score > 70 could be found."""
    return get_object_by_string(s, Track, 'title')


class Laptime(models.Model):
    track = models.ForeignKey("tracks.Track")
    player = models.ForeignKey("players.Player")
    created = models.DateTimeField(auto_now_add=True)
    recorded = models.DateField(null=True)
    vehicle = models.ForeignKey("vehicles.Vehicle")
    millis = models.IntegerField(default=0)
    millis_per_km = models.IntegerField(default=0)
    comment = models.TextField(default='', null=True, blank=True)
    video = EmbedVideoField(null=True)
    link = models.URLField(null=True)
    pc_60fps = models.BooleanField(default=False)

    class Meta:
        ordering=['-pk', ]

    def __str__(self):
        return '{0} {1}'.format(self.player.username,
                                self.vehicle.name)

    @property
    def duration(self):
        seco, mill = divmod(self.millis, 1000)
        minu, seco = divmod(seco, 60)
        return "{0}:{1:02}.{2:03}".format(int(minu), int(seco), int(mill))


    @property
    def km_per_h(self):
        if self.millis_per_km != 0:
            return '{:.3f}'.format(
                (1.0 / self.millis_per_km ) * 1000 * 3600
            )
        return '?'

    @property
    def linktype(self):
        """returns "l" for generic link, "v" for videolink, "" if no link at all"""
        hostname = urlparse(self.link).hostname
        VIDEOSITES = ('vimeo', 'youtu', 'dailymotio', 'twitch')
        if not hostname:
            return ""
        for hostpart in VIDEOSITES:
            if hostname.startswith(hostpart) or '.' + hostpart in hostname:
                return "film"
        return "link"

website/players/templates/players/change_password.html
{% extends "players/player_base.html" %}
{% load i18n %}

{% block title %}Change password for player {{ username }}{% endblock %}
{% block content %}

<h1>Change password for player {{ username }}</h1>
<form action="." method="POST">
{% csrf_token %}
New password: (will be displayed in plain text here)<br>
<input type="text" name="password">
<input type="submit" value="Set new password">
</form>
{% endblock %}

website/players/templates/players/player_base.html
{% extends "base.html" %}{% block menu_players_active %}active{% endblock %}

website/players/templates/players/player_detail.html
{% extends "players/player_base.html" %}
{% load i18n %}

{% block title %}Player {{ object.username }}{% endblock %}
{% block content %}

  <div class="row">
    <div class="col-md-12">
      <h1>{{ object.username }}
      {% if passwordlink %}
      <small class="pull-right">
        <a href="{% url "password_changer" passwordlink %}" class="btn btn-default">
          <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
          Change password</a>
      </small>

      {% endif %}
      </h1>
      <div class="row">
        <div class="col-md-6">
          <h2>Tracks maintained by {{ object.username }}</h2>
          <table id="tracktable" class="table table-striped table-bordered table-condensed">
            <thead>
            <th>_</th>
            <th>{% trans "Title" %}</th>
            <th>{% trans "Author" %}</th>
            </thead>
            <tbody>
            {% for track in object.track_set.all %}
              <tr>
                <td>{{ track.get_platform_display }}</td>
                <td><a href="{{ track.get_absolute_url }}">
                  {{ track.title }}</a>
                  {% if track.video %}
                    <span class="glyphicon glyphicon-film"></span>
                  {% endif %}
                  {% if track.image %}
                    <span class="glyphicon glyphicon-picture"></span>
                  {% endif %}
                </td>
                <td>{{ track.author }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="col-md-6">
          <h2>Hotlapping Events by {{ object.username }}</h2>
          <table id="hleventstable" class="table table-striped table-bordered table-condensed">
            <thead>
            <th>{% trans "Title" %}</th>
            <th>{% trans "Runtime" %}</th>
            </thead>
            <tbody>
            {% for hl in object.hotlapping_set.all %}
              <tr>
                <td><a href="{{ hl.get_absolute_url }}">
                  {{ hl.title }}</a>
                </td>
                <td>{{ hl.start_date|date:"Y-m-d H:i" }} – {{ hl.end_date|date:"Y-m-d H:i" }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>

        </div>
      </div>
      <h2>Laptimes</h2>
      <table id="playerlaptimetable" class="table table-striped table-bordered table-condensed">
        <thead>
        <th>{% trans "Track" %}</th>
        <th>{% trans "Vehicle" %}</th>
        <th>{% trans "Created" %}</th>
        <th>{% trans "Comment" %}</th>
        <th>{% trans "Link" %}</th>
        <th>{% trans "Time" %}</th>
        {% if request.user.pk == object.pk %}
          <th></th>
        {% endif %}
        </thead>
        <tbody>
        {% for l in object.laptime_set.all %}
          <tr>
            <td><a href="{% url "track_detail" l.track.pk %}">{{ l.track }}</a></td>
            <td><a href="{% url "vehicle_detail" l.vehicle.pk %}">{{ l.vehicle }}</a></td>
            <td>{{ l.created }}</td>
            <td>{{ l.comment }}</td>
            <td>{% if l.link %}
              <a href="{{ l.link }}" target="_blank"><span class="glyphicon glyphicon-link"></span></a>
            {% endif %}</td>
            <td>{{ l.duration }}</td>
            {% if request.user.pk == object.pk %}
              <td><a class="small" href="#" onclick="confirm('{{ l.pk }}');">
                <span class="glyphicon glyphicon-trash"></span>
              </a></td>
            {% endif %}

          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block trax_extra_script %}
  <script>
    var laptime_to_delete;
    function confirm(link) {
      laptime_to_delete = link;
      BootstrapDialog.confirm({
        title: 'Warning',
        message: 'Delete this lap time entry? You can not undo this action.',
        type: BootstrapDialog.TYPE_WARNING,
        closable: true,
        draggable: true,
        btnCancelLabel: "No, don't delete it!",
        btnOKLabel: "Yes, delete the entry!",
        btnOKClass: 'btn-warning',
        callback: function (result) {
          // result will be true if button was click, while it will be false if users close the dialog directly.
          if (result) {
            $.ajax({
              url: "/t/l/" + laptime_to_delete + "/delete/",
              success: function(data) {
                location.reload();
              }
            });
          }
        }
      });
    }

  </script>
{% endblock %}

website/players/templates/players/player_list.html
{% extends "players/player_base.html" %}
{% load i18n %}

{% block title %}Players{% endblock %}
{% block content %}

  <div class="row">
    <div class="col-md-12">
      <h1>The players</h1>
    <p>The "score" column may indicate how good players are, according
      to the lap times they entered. Lower values are better.
    But do not take this value really serious - it's just a dubious number
    calculated in a weird way that may change at any time.</p>
    <p>People with a score of 1.000 may not have entered lap times yet.</p>

      <table id="playerstable" class="table table-striped table-bordered table-condensed">
        <thead>
        <th>{% trans "Name" %}</th>
        <th>{% trans "Score" %}</th>
        </thead>
        <tbody>
        {% for p in object_list %}
          <tr>
            <td><a href="{{ p.get_absolute_url }}">{{ p.username }}</a></td>
            <td class="text-right">{{ p.defaultspeedmultiplier|floatformat:3 }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}